# Step Workload Scenario
# Ramps up in staircase fashion to evaluate throughput saturation and multi-stage autoscaling
locustfile = load-testing/locustfile.py
headless = true
host = http://localhost:30080
users = 35
spawn-rate = 5
run-time = 60s
