apiVersion: v1
kind: Service
metadata:
  name: ai-workload-service
  namespace: ai-workload
  labels:
    app: ai-workload-backend
    app.kubernetes.io/name: ai-workload-service
spec:
  type: NodePort
  selector:
    app: ai-workload-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
